name: presence
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.4
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^27.2.4

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
